name: CI

on:
  push:
    branches:
    - action
    tags:
    - '*'

jobs:
  build_and_release:
    name: proot-static
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
            sudo bash -c "${{ github.workspace }}/build.sh"

      - name: Build archlinux packages
        uses: countstarlight/arch-makepkg-action@master
        with:
          packages: >
            libxslt
            python-docutils
            talloc
          scripts: "makepkg"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            proot-static-*.tar.xz
            proot-me-*.pkg.tar.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
